require.config({
    baseUrl:"/",
    paths:{
        "jquery":"/lib/jquery/jquery-1.11.3",
        "header":"/js/module/header",
        "footer":"/js/module/footer",
        "url":"/js/module/url",
        "template":"/lib/art-template/template-web"
    }
})